 `pip install ipython-sql`
 
  This enables the sql below, run it in your environment if the cell below fails

# Lets just take a peak at our two tables

In [2]:
%%capture
%load_ext sql
%sql sqlite:///factbook.db

In [3]:
%%sql
SELECT *
  FROM facts
LIMIT 1;
# from facts | take 1

 * sqlite:///factbook.db
Done.
(sqlite3.OperationalError) unrecognized token: "#"
[SQL: # from facts | take 1]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

In [4]:
%%sql
SELECT *
  FROM cities
LIMIT 1;
# from cities | take 1

 * sqlite:///factbook.db
Done.

[(1, 'Oranjestad', 37000, 1, '216')]

## Whats this code thing about ?

In [6]:
%%sql
SELECT name, code, count(*) as row_count
from facts
GROUP BY code
LIMIT 5
# from facts
# select [name,code]
# aggregate by:[code] [count]
# take 5

 * sqlite:///factbook.db
Done.

[('Aruba', 'aa', 1),
 ('Antigua and Barbuda', 'ac', 1),
 ('United Arab Emirates', 'ae', 1),
 ('Afghanistan', 'af', 1),
 ('Algeria', 'ag', 1)]

# Looks like code is a unique country code , each row has facts for the country.

# Let look at cities

In [4]:
%%sql
SELECT *
from cities
         INNER JOIN facts on cities.facts_id = facts.id
LIMIT 4
#from cities
#join facts [facts_id = id]
#take 4

 * sqlite:///factbook.db
(sqlite3.OperationalError) near "#from": syntax error
[SQL: SELECT * from cities
         INNER JOIN facts on cities.facts_id = facts.id
LIMIT 4
#from cities
#join facts [facts_id = id]
#take 4]
(Background on this error at: https://sqlalche.me/e/14/e3q8)

# Now we have a list of all cities with their correponding country facts.  Lets group by country, so we look at countries with aggregated cities information

In [9]:
%%sql
SELECT cities.name                                                         as city,
       facts.name                                                          as country,
       cities.population                                                   as city_pop,
       round(100 * (1.0 / (facts.population / SUM(cities.population))), 2) as pct_pop_in_cities,
       facts.population                                                    as country_pop,
       SUM(cities.population)                                              as urban_pop,
       facts.population_growth,
       facts.birth_rate,
       facts.death_rate,
       facts.migration_rate
from cities
         INNER JOIN facts on cities.facts_id = facts.id
GROUP BY code
ORDER BY city_pop DESC
LIMIT 5

 * sqlite:///factbook.db
Done.

[('Tokyo', 'Japan', 37217000, 50.0, 126919659, 60077000, 0.16, 7.93, 9.51, 0.0),
 ('New Delhi', 'India', 22654000, 6.67, 1251695584, 82035000, 1.22, 19.55, 7.32, 0.04),
 ('Mexico City', 'Mexico', 20446000, 33.33, 121736809, 33449000, 1.18, 18.78, 5.26, 1.68),
 ('New York-Newark', 'United States', 20352000, 20.0, 321368864, 60116000, 0.78, 12.49, 8.15, 3.86),
 ('Shanghai', 'China', 20208000, 5.0, 1367485388, 66849000, 0.45, 12.49, 7.53, 0.44)]


# Now we have the worlds countries sorted by their largest cities size, along with *pct_pop_in_cities* which we created, comparing the size in the cities to the countries population.  We can sort by that later to see which countries are the densest.

# Lets see how big each cities capital is compared to its country

In [35]:
%%sql
SELECT cities.name as capital,
       facts.name as country,
       cities.population as city_pop,
       facts.population as country_pop,
       round(CAST(cities.population as float) / CAST(facts.population as float),2) as pop_ratio
from cities
         LEFT JOIN facts on cities.facts_id = facts.id
where capital = 1
ORDER BY cities.name

 * sqlite:///factbook.db
Done.

[('Abu Dhabi', 'United Arab Emirates', 942000, 5779760, 0.16),
 ('Abuja', 'Nigeria', 2153000, 181562056, 0.01),
 ('Accra', 'Ghana', 2573000, 26327649, 0.1),
 ('Addis Ababa', 'Ethiopia', 2979000, 99465819, 0.03),
 ('Algiers', 'Algeria', 2916000, 39542166, 0.07),
 ('Amman', 'Jordan', 1179000, 8117564, 0.15),
 ('Amsterdam', 'Netherlands', 1056000, 16947904, 0.06),
 ('Andorra La Vella', 'Andorra', 23000, 85580, 0.27),
 ('Ankara', 'Turkey', 4194000, 79414269, 0.05),
 ('Antananarivo', 'Madagascar', 1987000, 23812681, 0.08),
 ('Apia', 'Samoa', 37000, 197773, 0.19),
 ('Ashgabat', 'Turkmenistan', 683000, 5231422, 0.13),
 ('Asmara', 'Eritrea', 712000, 6527689, 0.11),
 ('Astana', 'Kazakhstan', 664000, 18157122, 0.04),
 ('Asuncion', 'Paraguay', 2139000, 6783272, 0.32),
 ('Athens', 'Greece', 3414000, 10775643, 0.32),
 ('Baghdad', 'Iraq', 6036000, 37056169, 0.16),
 ('Baku', 'Azerbaijan', 2123000, 9780780, 0.22),
 ('Bamako', 'Mali', 2037000, 16955536, 0.12),
 ('Bandar Seri Begawan', 'Brunei', 241000, 429646, 0.56),
 ('Bangkok', 'Thailand', 8426000, 67976405, 0.12),
 ('Bangui', 'Central African Republic', 740000, 5391539, 0.14),
 ('Banjul', 'Gambia, The', 506000, 1967709, 0.26),
 ('Basseterre', 'Saint Kitts and Nevis', 12000, 51936, 0.23),
 ('Beijing', 'China', 15594000, 1367485388, 0.01),
 ('Beirut', 'Lebanon', 2022000, 6184701, 0.33),
 ('Belgrade', 'Serbia', 1135000, 7176794, 0.16),
 ('Belmopan', 'Belize', 14000, 347369, 0.04),
 ('Berlin', 'Germany', 3462000, 80854408, 0.04),
 ('Bern', 'Switzerland', 353000, 8121830, 0.04),
 ('Bishkek', 'Kyrgyzstan', 839000, 5664939, 0.15),
 ('Bissau', 'Guinea-Bissau', 423000, 1726170, 0.25),
 ('Bogota', 'Colombia', 8743000, 46736728, 0.19),
 ('Brasilia', 'Brazil', 3813000, 204259812, 0.02),
 ('Bratislava', 'Slovakia', 434000, 5445027, 0.08),
 ('Brazzaville', 'Congo, Republic of the', 1611000, 4755097, 0.34),
 ('Bridgetown', 'Barbados', 122000, 290604, 0.42),
 ('Brussels', 'Belgium', 1949000, 11323973, 0.17),
 ('Bucharest', 'Romania', 1937000, 21666350, 0.09),
 ('Budapest', 'Hungary', 1737000, 9897541, 0.18),
 ('Buenos Aires', 'Argentina', 13528000, 43431886, 0.31),
 ('Bujumbura', 'Burundi', 605000, 10742276, 0.06),
 ('Cairo', 'Egypt', 11169000, 88487396, 0.13),
 ('Canberra', 'Australia', 399000, 22751014, 0.02),
 ('Caracas', 'Venezuela', 3242000, 29275460, 0.11),
 ('Castries', 'Saint Lucia', 21000, 163922, 0.13),
 ('Charlotte Amalie', 'Virgin Islands', 60000, 103574, 0.58),
 ('Chisinau', 'Moldova', 677000, 3546847, 0.19),
 ('Colombo', 'Sri Lanka', 693000, 22053488, 0.03),
 ('Conakry', 'Guinea', 1786000, 11780162, 0.15),
 ('Copenhagen', 'Denmark', 1206000, 5581503, 0.22),
 ('Dakar', 'Senegal', 3035000, 13975834, 0.22),
 ('Damascus', 'Syria', 265000, 17064854, 0.02),
 ('Dar Es Salaam', 'Tanzania', 3588000, 51045882, 0.07),
 ('Dhaka', 'Bangladesh', 15391000, 168957745, 0.09),
 ('Dili', 'Timor-Leste', 180000, 1231116, 0.15),
 ('Djibouti', 'Djibouti', 496000, 828324, 0.6),
 ('Doha', 'Qatar', 567000, 2194817, 0.26),
 ('Douglas', 'Isle of Man', 27000, 87545, 0.31),
 ('Dublin', 'Ireland', 1121000, 4892305, 0.23),
 ('Dushanbe', 'Tajikistan', 739000, 8191958, 0.09),
 ('Freetown', 'Sierra Leone', 941000, 5879098, 0.16),
 ('Funafuti', 'Tuvalu', 5000, 10869, 0.46),
 ('Gaborone', 'Botswana', 202000, 2182719, 0.09),
 ('George Town', 'Cayman Islands', 28000, 56092, 0.5),
 ('Georgetown', 'Guyana', 127000, 735222, 0.17),
 ('Grand Turk', 'Turks and Caicos Islands', 7000, 50280, 0.14),
 ('Guatemala City', 'Guatemala', 1168000, 14918999, 0.08),
 ('Hagatna', 'Guam', 169000, 161785, 1.04),
 ('Hamilton', 'Bermuda', 11000, 70196, 0.16),
 ('Hanoi', 'Vietnam', 2955000, 94348835, 0.03),
 ('Harare', 'Zimbabwe', 1542000, 14229541, 0.11),
 ('Havana', 'Cuba', 2116000, 11031433, 0.19),
 ('Helsinki', 'Finland', 1134000, 5476922, 0.21),
 ('Honiara', 'Solomon Islands', 68000, 622469, 0.11),
 ('Islamabad', 'Pakistan', 919000, 199085847, 0.0),
 ('Jakarta', 'Indonesia', 9769000, 255993674, 0.04),
 ('Jamestown', 'Saint Helena, Ascension, and Tristan da Cunha', 1000, 7795, 0.13),
 ('Jerusalem', 'Israel', 791000, 8049314, 0.1),
 ('Juba', 'South Sudan', 269000, 12042910, 0.02),
 ('Kabul', 'Afghanistan', 3097000, 32564342, 0.1),
 ('Kampala', 'Uganda', 1659000, 37101745, 0.04),
 ('Kathmandu', 'Nepal', 1015000, 31551305, 0.03),
 ('Khartoum', 'Sudan', 4632000, 36108853, 0.13),
 ('Kigali', 'Rwanda', 1004000, 12661733, 0.08),
 ('Kingston', 'Jamaica', 571000, 2950210, 0.19),
 ('Kingstown', 'Saint Vincent and the Grenadines', 31000, 102627, 0.3),
 ('Kinshasa', 'Congo, Democratic Republic of the', 8798000, 79375136, 0.11),
 ('Kuala Lumpur', 'Malaysia', 1556000, 30513848, 0.05),
 ('Kuwait', 'Kuwait', 2406000, 2788534, 0.86),
 ('Kyiv', 'Ukraine', 2829000, 44429471, 0.06),
 ('La Paz', 'Bolivia', 1715000, 10800882, 0.16),
 ('Libreville', 'Gabon', 686000, 1705336, 0.4),
 ('Lilongwe', 'Malawi', 772000, 17964697, 0.04),
 ('Lima', 'Peru', 913000, 30444999, 0.03),
 ('Lisbon', 'Portugal', 2843000, 10825309, 0.26),
 ('Ljubljana', 'Slovenia', 273000, 1983412, 0.14),
 ('Lome', 'Togo', 1524000, 7552318, 0.2),
 ('London', 'United Kingdom', 9005000, 64088222, 0.14),
 ('Luanda', 'Angola', 5068000, 19625353, 0.26),
 ('Lusaka', 'Zambia', 1802000, 15066266, 0.12),
 ('Luxembourg', 'Luxembourg', 94000, 570252, 0.16),
 ('Madrid', 'Spain', 6574000, 48146134, 0.14),
 ('Majuro', 'Marshall Islands', 31000, 72191, 0.43),
 ('Malabo', 'Equatorial Guinea', 137000, 740743, 0.18),
 ('Male', 'Maldives', 132000, 393253, 0.34),
 ('Managua', 'Nicaragua', 970000, 5907881, 0.16),
 ('Manama', 'Bahrain', 262000, 1346613, 0.19),
 ('Manila', 'Philippines', 11862000, 100998376, 0.12),
 ('Maputo', 'Mozambique', 115000, 25303113, 0.0),
 ('Maseru', 'Lesotho', 239000, 1947701, 0.12),
 ('Mata-Utu', 'Wallis and Futuna', 1000, 15613, 0.06),
 ('Mbabane', 'Swaziland', 66000, 1435613, 0.05),
 ('Melekeok', 'Palau', 1000, 21265, 0.05),
 ('Mexico City', 'Mexico', 20446000, 121736809, 0.17),
 ('Minsk', 'Belarus', 1861000, 9589689, 0.19),
 ('Mogadishu', 'Somalia', 1554000, 10616380, 0.15),
 ('Monrovia', 'Liberia', 750000, 4195666, 0.18),
 ('Montevideo', 'Uruguay', 1672000, 3341893, 0.5),
 ('Moroni', 'Comoros', 54000, 780971, 0.07),
 ('Moscow', 'Russia', 11621000, 142423773, 0.08),
 ('Muscat', 'Oman', 743000, 3286936, 0.23),
 ("N'Djamena", 'Chad', 1079000, 11631456, 0.09),
 ('Nairobi', 'Kenya', 3363000, 45925301, 0.07),
 ('Nassau', 'Bahamas, The', 254000, 324597, 0.78),
 ('New Delhi', 'India', 22654000, 1251695584, 0.02),
 ('Niamey', 'Niger', 1297000, 18045729, 0.07),
 ('Nicosia', 'Cyprus', 253000, 1189197, 0.21),
 ('Nouakchott', 'Mauritania', 786000, 3596702, 0.22),
 ('Noumea', 'New Caledonia', 157000, 271615, 0.58),
 ('Nuuk', 'Greenland', 16000, 57733, 0.28),
 ('Oranjestad', 'Aruba', 37000, 112162, 0.33),
 ('Oslo', 'Norway', 915000, 5207689, 0.18),
 ('Ottawa', 'Canada', 1208000, 35099836, 0.03),
 ('Ouagadougou', 'Burkina Faso', 2053000, 18931686, 0.11),
 ('Pago Pago', 'American Samoa', 64000, 54343, 1.18),
 ('Palikir', 'Micronesia, Federated States of', 7000, 105216, 0.07),
 ('Panama City', 'Panama', 1426000, 3657024, 0.39),
 ('Papeete', 'French Polynesia', 137000, 282703, 0.48),
 ('Paramaribo', 'Suriname', 278000, 579633, 0.48),
 ('Paris', 'France', 1062000, 66553766, 0.02),
 ('Phnom Penh', 'Cambodia', 155000, 15708756, 0.01),
 ('Podgorica', 'Montenegro', 156000, 647073, 0.24),
 ('Port Louis', 'Mauritius', 151000, 1339827, 0.11),
 ('Port Moresby', 'Papua New Guinea', 343000, 6672429, 0.05),
 ('Port-Au-Prince', 'Haiti', 2207000, 10110019, 0.22),
 ('Port-Of-Spain', 'Trinidad and Tobago', 66000, 1222363, 0.05),
 ('Port-Vila', 'Vanuatu', 47000, 272264, 0.17),
 ('Porto-Novo', 'Benin', 314000, 10448647, 0.03),
 ('Prague', 'Czech Republic', 1276000, 10644842, 0.12),
 ('Praia', 'Cabo Verde', 132000, 545993, 0.24),
 ('Pretoria', 'South Africa', 1501000, 53675563, 0.03),
 ('Pyongyang', 'Korea, North', 2843000, 24983205, 0.11),
 ('Quito', 'Ecuador', 1622000, 15868396, 0.1),
 ('Rabat', 'Morocco', 1843000, 33322699, 0.06),
 ('Rangoon', 'Burma', 4457000, 56320206, 0.08),
 ('Reykjavik', 'Iceland', 206000, 331918, 0.62),
 ('Riga', 'Latvia', 701000, 1986705, 0.35),
 ('Riyadh', 'Saudi Arabia', 5451000, 27752316, 0.2),
 ('Road Town', 'British Virgin Islands', 10000, 33454, 0.3),
 ('Rome', 'Italy', 3298000, 61855120, 0.05),
 ('Roseau', 'Dominica', 14000, 73607, 0.19),
 ("Saint George'S", 'Grenada', 41000, 110694, 0.37),
 ("Saint John'S", 'Antigua and Barbuda', 27000, 92436, 0.29),
 ('Saint-Pierre', 'Saint Pierre and Miquelon', 5000, 5657, 0.88),
 ('Saipan', 'Northern Mariana Islands', 56000, 52344, 1.07),
 ('San Jose', 'Costa Rica', 1515000, 4814144, 0.31),
 ('San Juan', 'Puerto Rico', 2475000, 3598357, 0.69),
 ('San Salvador', 'El Salvador', 1605000, 6141350, 0.26),
 ('Sanaa', 'Yemen', 2419000, 26737317, 0.09),
 ('Santiago', 'Chile', 6034000, 17508260, 0.34),
 ('Santo Domingo', 'Dominican Republic', 2191000, 10478756, 0.21),
 ('Sao Tome', 'Sao Tome and Principe', 64000, 194006, 0.33),
 ('Sarajevo', 'Bosnia and Herzegovina', 389000, 3867055, 0.1),
 ('Seoul', 'Korea, South', 9736000, 49115196, 0.2),
 ('Skopje', 'Macedonia', 499000, 2096015, 0.24),
 ('Sofia', 'Bulgaria', 1174000, 7186893, 0.16),
 ('Stanley', 'Falkland Islands (Islas Malvinas)', 2000, 3361, 0.6),
 ('Stockholm', 'Sweden', 1385000, 9801616, 0.14),
 ('Suva', 'Fiji', 177000, 909389, 0.19),
 ('Tallinn', 'Estonia', 400000, 1265420, 0.32),
 ('Tarawa', 'Kiribati', 44000, 105711, 0.42),
 ('Tashkent', 'Uzbekistan', 2227000, 29199942, 0.08),
 ('Tbilisi', 'Georgia', 1121000, 4931226, 0.23),
 ('Tegucigalpa', 'Honduras', 1088000, 8746673, 0.12),
 ('Tehran', 'Iran', 7304000, 81824270, 0.09),
 ('The Valley', 'Anguilla', 2000, 16418, 0.12),
 ('Thimphu', 'Bhutan', 99000, 741919, 0.13),
 ('Tirana', 'Albania', 419000, 3029278, 0.14),
 ('Tokyo', 'Japan', 37217000, 126919659, 0.29),
 ('Torshavn', 'Faroe Islands', 20000, 50196, 0.4),
 ('Tripoli', 'Libya', 1127000, 6411776, 0.18),
 ('Tunis', 'Tunisia', 790000, 11037225, 0.07),
 ('Ulaanbaatar', 'Mongolia', 1184000, 2992908, 0.4),
 ('Vaduz', 'Liechtenstein', 5000, 37624, 0.13),
 ('Valletta', 'Malta', 198000, 413965, 0.48),
 ('Victoria', 'Seychelles', 27000, 92430, 0.29),
 ('Vienna', 'Austria', 172000, 8665550, 0.02),
 ('Vientiane', 'Laos', 810000, 6911544, 0.12),
 ('Vilnius', 'Lithuania', 546000, 2884433, 0.19),
 ('Warsaw', 'Poland', 1723000, 38562189, 0.04),
 ('Washington, D.C.', 'United States', 4705000, 321368864, 0.01),
 ('Wellington', 'New Zealand', 410000, 4438393, 0.09),
 ('Windhoek', 'Namibia', 380000, 2212307, 0.17),
 ('Yamoussoukro', "Cote d'Ivoire", 966000, 23295302, 0.04),
 ('Yaounde', 'Cameroon', 2432000, 23739218, 0.1),
 ('Yerevan', 'Armenia', 1116000, 3056382, 0.37),
 ('Zagreb', 'Croatia', 686000, 4464844, 0.15)]